#Embedded file name: dropbox/sync_engine_file_system/windows_error.py
import errno
_winerror_to_errno_map = {2: 2,
 3: 2,
 4: 24,
 5: 13,
 6: 9,
 7: 12,
 8: 12,
 9: 12,
 10: 7,
 11: 8,
 15: 2,
 16: 13,
 17: 18,
 18: 2,
 19: 13,
 20: 13,
 21: 13,
 22: 13,
 23: 13,
 24: 13,
 25: 13,
 26: 13,
 27: 13,
 28: 13,
 29: 13,
 30: 13,
 31: 13,
 32: 13,
 33: 13,
 34: 13,
 35: 13,
 36: 13,
 53: 2,
 65: 13,
 67: 2,
 80: 17,
 82: 13,
 83: 13,
 89: 11,
 108: 13,
 109: 32,
 112: 28,
 114: 9,
 128: 10,
 129: 10,
 130: 9,
 131: 13,
 132: 13,
 145: 41,
 158: 13,
 161: 2,
 164: 11,
 167: 13,
 183: 17,
 188: 8,
 189: 8,
 190: 8,
 191: 8,
 192: 8,
 193: 8,
 194: 8,
 195: 8,
 196: 8,
 197: 8,
 198: 8,
 199: 8,
 200: 8,
 201: 8,
 202: 8,
 206: errno.ENAMETOOLONG,
 215: 11,
 1816: 12}

def windows_error_to_errno(e):
    return _winerror_to_errno_map.get(e, errno.EINVAL)
